language: r
cache: packages
sudo: required

before_install:
  - sudo update-alternatives  --set python /usr/bin/python3.8
  - pip install sma numpy

r_packages:
   - testthat
   - reticulate

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    
addons:
  apt:
    update: true
    packages:
      - libmagick++-dev
      - python3.8
