dist: bionic
language: r
cache: packages
sudo: required
warnings_are_errors: false

r_packages:
   - testthat
   - reticulate
   - pkgdown
   - devtools 

before_install:
 - python3 -m pip install numpy networkx sma
 
after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    
addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
