dist: bionic
language: r
cache: packages
sudo: required
warnings_are_errors: false

r_packages:
   - testthat
   - reticulate
   - pkgdown
   - knitr
   - devtools

# https://www.jumpingrivers.com/blog/r-packages-travis-github-actions-rstudio/
before_install:
 - python3 -m pip install numpy networkx sma
# - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest'))" >> ~/.Rprofile.site
# - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
#       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
#       ')'))" >> ~/.Rprofile.site

after_success:
  # re-build pre-build vignettes since they have not been build properly yet
  - echo "Pre-building vignette from ${PKG_TARBALL}"
  - R CMD INSTALL "${PKG_TARBALL}" 
  - Rscript vignettes/precompile.R
  - Rscript -e 'devtools::build_vignettes()'
  # build website
  - Rscript -e 'pkgdown::build_site(run_dont_run = TRUE)'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local-dir: docs
  on:
    branch: master

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - libmagick++-dev
      - libharfbuzz-dev
      - libfribidi-dev
